# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session:
        # The system PHP session directory is not writable by the Symfony CLI user.
        save_path: '%kernel.project_dir%/var/sessions'

    #esi: true
    #fragments: true

    rate_limiter:
        contact_api:
            policy: sliding_window
            limit: 5
            interval: '1 hour'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
