<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261006205152 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Convert key_figure.id from integer identity to UUID';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE key_figure DROP CONSTRAINT key_figure_pkey');
        $this->addSql('ALTER TABLE key_figure ALTER id DROP IDENTITY IF EXISTS');
        $this->addSql('ALTER TABLE key_figure DROP COLUMN id');
        $this->addSql('ALTER TABLE key_figure ADD id UUID NOT NULL');
        $this->addSql('ALTER TABLE key_figure ADD PRIMARY KEY (id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE key_figure DROP CONSTRAINT key_figure_pkey');
        $this->addSql('ALTER TABLE key_figure DROP COLUMN id');
        $this->addSql('ALTER TABLE key_figure ADD id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL');
        $this->addSql('ALTER TABLE key_figure ADD PRIMARY KEY (id)');
    }
}
