<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261006204557 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE key_figure (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, figure VARCHAR(32) NOT NULL, label VARCHAR(64) NOT NULL, priority INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('COMMENT ON COLUMN contact.id IS \'\'');
        $this->addSql('COMMENT ON COLUMN contact.controversy_id IS \'\'');
        $this->addSql('COMMENT ON COLUMN contact.created_at IS \'\'');
        $this->addSql('ALTER TABLE controversy ALTER is_visible DROP DEFAULT');
        $this->addSql('ALTER TABLE person ALTER is_visible DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE key_figure');
        $this->addSql('COMMENT ON COLUMN contact.id IS \'(DC2Type:uuid)\'');
        $this->addSql('COMMENT ON COLUMN contact.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN contact.controversy_id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE controversy ALTER is_visible SET DEFAULT true');
        $this->addSql('ALTER TABLE person ALTER is_visible SET DEFAULT true');
    }
}
