<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261003200343 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add themes and their link to controversies';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE controversy_theme (controversy_id UUID NOT NULL, theme_id INT NOT NULL, PRIMARY KEY (controversy_id, theme_id))');
        $this->addSql('CREATE INDEX IDX_8A77599F3264675D ON controversy_theme (controversy_id)');
        $this->addSql('CREATE INDEX IDX_8A77599F59027487 ON controversy_theme (theme_id)');
        $this->addSql('CREATE TABLE theme (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(32) NOT NULL, color VARCHAR(16) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE controversy_theme ADD CONSTRAINT FK_8A77599F3264675D FOREIGN KEY (controversy_id) REFERENCES controversy (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE controversy_theme ADD CONSTRAINT FK_8A77599F59027487 FOREIGN KEY (theme_id) REFERENCES theme (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE controversy_theme DROP CONSTRAINT FK_8A77599F3264675D');
        $this->addSql('ALTER TABLE controversy_theme DROP CONSTRAINT FK_8A77599F59027487');
        $this->addSql('DROP TABLE controversy_theme');
        $this->addSql('DROP TABLE theme');
    }
}
