<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261001173345 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Replace the person legal entity link with an association';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE person_legal_entity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date DATE NOT NULL, end_date DATE DEFAULT NULL, position VARCHAR(255) DEFAULT NULL, person_id INT NOT NULL, legal_entity_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1107E5E217BBB47 ON person_legal_entity (person_id)');
        $this->addSql('CREATE INDEX IDX_1107E5E6DEC420C ON person_legal_entity (legal_entity_id)');
        $this->addSql('ALTER TABLE person_legal_entity ADD CONSTRAINT FK_1107E5E217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE person_legal_entity ADD CONSTRAINT FK_1107E5E6DEC420C FOREIGN KEY (legal_entity_id) REFERENCES legal_entity (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE person DROP CONSTRAINT fk_34dcd1766dec420c');
        $this->addSql('DROP INDEX idx_34dcd1766dec420c');
        $this->addSql('ALTER TABLE person DROP "position"');
        $this->addSql('ALTER TABLE person DROP legal_entity_id');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE person_legal_entity DROP CONSTRAINT FK_1107E5E217BBB47');
        $this->addSql('ALTER TABLE person_legal_entity DROP CONSTRAINT FK_1107E5E6DEC420C');
        $this->addSql('DROP TABLE person_legal_entity');
        $this->addSql('ALTER TABLE person ADD "position" VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE person ADD legal_entity_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT fk_34dcd1766dec420c FOREIGN KEY (legal_entity_id) REFERENCES legal_entity (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_34dcd1766dec420c ON person (legal_entity_id)');
    }
}
