<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261001171822 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the domain tables';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE controversy (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(64) NOT NULL, short_description VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE controversy_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(32) NOT NULL, title VARCHAR(128) NOT NULL, date DATE NOT NULL, is_visible BOOLEAN NOT NULL, controversy_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AAB5D60E3264675D ON controversy_item (controversy_id)');
        $this->addSql('CREATE TABLE controversy_item_person (controversy_item_id INT NOT NULL, person_id INT NOT NULL, PRIMARY KEY (controversy_item_id, person_id))');
        $this->addSql('CREATE INDEX IDX_A346CC9FB6CD0A ON controversy_item_person (controversy_item_id)');
        $this->addSql('CREATE INDEX IDX_A346CC9F217BBB47 ON controversy_item_person (person_id)');
        $this->addSql('CREATE TABLE legal_entity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(64) NOT NULL, short_description VARCHAR(255) NOT NULL, website VARCHAR(255) DEFAULT NULL, type VARCHAR(32) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE party (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(64) NOT NULL, color VARCHAR(16) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE person (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, firstname VARCHAR(64) NOT NULL, lastname VARCHAR(64) NOT NULL, position VARCHAR(255) DEFAULT NULL, legal_entity_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_34DCD1766DEC420C ON person (legal_entity_id)');
        $this->addSql('CREATE TABLE person_party (person_id INT NOT NULL, party_id INT NOT NULL, PRIMARY KEY (person_id, party_id))');
        $this->addSql('CREATE INDEX IDX_25A35124217BBB47 ON person_party (person_id)');
        $this->addSql('CREATE INDEX IDX_25A35124213C1059 ON person_party (party_id)');
        $this->addSql('CREATE TABLE source (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, url VARCHAR(255) NOT NULL, is_visible BOOLEAN NOT NULL, controversy_item_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5F8A7F73B6CD0A ON source (controversy_item_id)');
        $this->addSql('ALTER TABLE controversy_item ADD CONSTRAINT FK_AAB5D60E3264675D FOREIGN KEY (controversy_id) REFERENCES controversy (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE controversy_item_person ADD CONSTRAINT FK_A346CC9FB6CD0A FOREIGN KEY (controversy_item_id) REFERENCES controversy_item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE controversy_item_person ADD CONSTRAINT FK_A346CC9F217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD1766DEC420C FOREIGN KEY (legal_entity_id) REFERENCES legal_entity (id)');
        $this->addSql('ALTER TABLE person_party ADD CONSTRAINT FK_25A35124217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE person_party ADD CONSTRAINT FK_25A35124213C1059 FOREIGN KEY (party_id) REFERENCES party (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE source ADD CONSTRAINT FK_5F8A7F73B6CD0A FOREIGN KEY (controversy_item_id) REFERENCES controversy_item (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE controversy_item DROP CONSTRAINT FK_AAB5D60E3264675D');
        $this->addSql('ALTER TABLE controversy_item_person DROP CONSTRAINT FK_A346CC9FB6CD0A');
        $this->addSql('ALTER TABLE controversy_item_person DROP CONSTRAINT FK_A346CC9F217BBB47');
        $this->addSql('ALTER TABLE person DROP CONSTRAINT FK_34DCD1766DEC420C');
        $this->addSql('ALTER TABLE person_party DROP CONSTRAINT FK_25A35124217BBB47');
        $this->addSql('ALTER TABLE person_party DROP CONSTRAINT FK_25A35124213C1059');
        $this->addSql('ALTER TABLE source DROP CONSTRAINT FK_5F8A7F73B6CD0A');
        $this->addSql('DROP TABLE controversy');
        $this->addSql('DROP TABLE controversy_item');
        $this->addSql('DROP TABLE controversy_item_person');
        $this->addSql('DROP TABLE legal_entity');
        $this->addSql('DROP TABLE party');
        $this->addSql('DROP TABLE person');
        $this->addSql('DROP TABLE person_party');
        $this->addSql('DROP TABLE source');
    }
}
